# -*- coding: utf-8 -*-
"""NPS_Switch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jonTQ-BWP6FAE-6nxk5MwyDiA8Ir11Ij
"""

import yfinance as yf
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import os
import subprocess
import warnings
warnings.filterwarnings("ignore")

print("Running Evening NPS Strategy Check...")

# 1. Download Nifty 50 Data
df = yf.download("^NSEI", start="2018-01-01", progress=False)
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.droplevel(1)
df = df[['Close', 'High', 'Low']].copy()

# 2. Fetch Current India 10Y Bond Yield from Trading Economics
def fetch_trading_economics_yield():
    try:
        url = "https://tradingeconomics.com/india/government-bond-yield"
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            val_elem = soup.find('td', {'id': 'p'}) or soup.find('span', {'id': 'actual-value'})
            if val_elem:
                return float(val_elem.text.strip())
    except Exception as e:
        print(f"Live web fetch fallback triggered: {e}")
    return 6.83

current_gsec_yield = fetch_trading_economics_yield()

def get_gsec_yield(date):
    year = date.year
    yield_map = {2018: 7.50, 2019: 6.80, 2020: 6.00, 2021: 6.35,
                 2022: 7.30, 2023: 7.20, 2024: 7.10, 2025: 6.85, 2026: current_gsec_yield}
    return yield_map.get(year, current_gsec_yield)

df['Yield_10Y'] = [get_gsec_yield(d) for d in df.index]

# 3. Strategy Indicators & Triggers
delta = df['Close'].diff()
up = delta.clip(lower=0)
down = -1 * delta.clip(upper=0)
ema_up = up.ewm(com=13, adjust=False).mean()
ema_down = down.ewm(com=13, adjust=False).mean()
df['RSI'] = 100 - (100 / (1 + (ema_up / ema_down)))

fast_ema = df['Close'].ewm(span=12, adjust=False).mean()
slow_ema = df['Close'].ewm(span=26, adjust=False).mean()
df['MACD'] = fast_ema - slow_ema

lookback = 5
window = 2 * lookback + 1
df['Local_Min'] = df['Low'].rolling(window=window).min()
df['Pivot_Low_Found'] = df['Low'].shift(lookback) == df['Local_Min']
df['Pivot_Low_Price'] = np.where(df['Pivot_Low_Found'], df['Low'].shift(lookback), np.nan)
df['Pivot_Low_RSI'] = np.where(df['Pivot_Low_Found'], df['RSI'].shift(lookback), np.nan)
df['Pivot_Low_MACD'] = np.where(df['Pivot_Low_Found'], df['MACD'].shift(lookback), np.nan)
df['Prev_Low_Price'] = df['Pivot_Low_Price'].ffill().shift(1)
df['Prev_Low_RSI'] = df['Pivot_Low_RSI'].ffill().shift(1)
df['Prev_Low_MACD'] = df['Pivot_Low_MACD'].ffill().shift(1)

df['Local_Max'] = df['High'].rolling(window=window).max()
df['Pivot_High_Found'] = df['High'].shift(lookback) == df['Local_Max']
df['Pivot_High_Price'] = np.where(df['Pivot_High_Found'], df['High'].shift(lookback), np.nan)
df['Pivot_High_RSI'] = np.where(df['Pivot_High_Found'], df['RSI'].shift(lookback), np.nan)
df['Pivot_High_MACD'] = np.where(df['Pivot_High_Found'], df['MACD'].shift(lookback), np.nan)
df['Prev_High_Price'] = df['Pivot_High_Price'].ffill().shift(1)
df['Prev_High_RSI'] = df['Pivot_High_RSI'].ffill().shift(1)
df['Prev_High_MACD'] = df['Pivot_High_MACD'].ffill().shift(1)

df['Bull_Div'] = df['Pivot_Low_Found'] & (df['Pivot_Low_Price'] < df['Prev_Low_Price']) & (df['Pivot_Low_RSI'] > df['Prev_Low_RSI']) & (df['Pivot_Low_MACD'] > df['Prev_Low_MACD'])
df['Bear_Div'] = df['Pivot_High_Found'] & (df['Pivot_High_Price'] > df['Prev_High_Price']) & (df['Pivot_High_RSI'] < df['Prev_High_RSI']) & (df['Pivot_High_MACD'] < df['Prev_High_MACD'])

df['High_52W'] = df['High'].rolling(252, min_periods=1).max()
df['Current_DD'] = (df['Close'] - df['High_52W']) / df['High_52W']
df['Panic_Buy_DD'] = df['Current_DD'] <= -0.20

df['SMA_20'] = df['Close'].rolling(20).mean()
df['STD_20'] = df['Close'].rolling(20).std()
df['Lower_BB'] = df['SMA_20'] - (2.5 * df['STD_20'])
df['V_Bottom_Buy'] = (df['Close'].shift(1) < df['Lower_BB'].shift(1)) & (df['Close'] > df['Lower_BB'])

df['Hybrid_Buy'] = df['Bull_Div'] | df['Panic_Buy_DD'] | df['V_Bottom_Buy']

# Simulation Loop
positions = []
curr_pos = 1
switches_fy = 0
current_fy = None

for i in range(len(df)):
    date = df.index[i]
    fy = date.year if date.month >= 4 else date.year - 1
    if fy != current_fy:
        current_fy = fy
        switches_fy = 0
    buy_sig = df['Hybrid_Buy'].iloc[i]
    sell_sig = df['Bear_Div'].iloc[i]
    desired_pos = curr_pos
    if buy_sig: desired_pos = 1
    elif sell_sig: desired_pos = 0
    if desired_pos != curr_pos:
        if switches_fy < 4:
            curr_pos = desired_pos
            switches_fy += 1
    positions.append(curr_pos)

df['Signal_Position'] = positions
df['Position'] = df['Signal_Position'].shift(2).fillna(1)

# Current Evaluation
latest_pos = int(df['Position'].iloc[-1])
latest_date = df.index[-1].strftime('%Y-%m-%d')
nifty_close = df['Close'].iloc[-1]
current_status_str = "Scheme E (Equity)" if latest_pos == 1 else "Scheme G (Debt)"

# 4. Check State Memory from local repository file
state_file_path = 'nps_last_status.txt'
previous_status_str = "Unknown"
if os.path.exists(state_file_path):
    with open(state_file_path, 'r') as f:
        previous_status_str = f.read().strip()

print(f"Current Model Status: {current_status_str} | Previous Saved Status: {previous_status_str}")

# 5. Conditional Telegram Alert Trigger & State Update
if current_status_str != previous_status_str:
    print("Trigger switch detected! Sending Telegram push alert...")

    bot_token = os.environ.get('TELEGRAM_TOKEN')
    chat_id = os.environ.get('CHAT_ID')

    message = (
        f"🚨 *NPS STRATEGY SWITCH TRIGGERED* 🚨\n\n"
        f"• *Date:* {latest_date}\n"
        f"• *Nifty Close:* {nifty_close:.2f}\n"
        f"• *New Allocation:* *{current_status_str}*\n\n"
        f"Log into your CRA/NPS portal to execute the reallocation."
    )

    telegram_url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "Markdown"
    }

    response = requests.post(telegram_url, json=payload)
    if response.status_code == 200:
        print("Telegram push notification sent successfully.")
    else:
        print(f"Failed to send Telegram alert: {response.text}")

    # Write new status to file
    with open(state_file_path, 'w') as f:
        f.write(current_status_str)

    # Automatically commit and push the updated state back to GitHub
    try:
        subprocess.run(["git", "config", "--global", "user.name", "NPS Bot"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "bot@users.noreply.github.com"], check=True)
        subprocess.run(["git", "add", state_file_path], check=True)
        subprocess.run(["git", "commit", "-m", f"Update state to {current_status_str}"], check=True)
        subprocess.run(["git", "push"], check=True)
        print("Successfully updated state file in GitHub repository.")
    except Exception as git_err:
        print(f"Git auto-commit failed: {git_err}")
else:
    print("No change in strategy position. No notification sent.")
